FROM node:20-alpine
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Use development mode
ENV NODE_ENV=development

# Run NestJS dev mode
CMD ["npm", "run", "start:dev"]
