version: '3.8'

services:
  backend:
    build: .
    container_name: simastemu-backend
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    environment:
      DB_HOST: db
    depends_on:
      - db
    volumes:
      - ./uploads:/usr/src/app/uploads

  db:
    image: postgres:17-alpine
    container_name: simastemu-db
    env_file:
      - .env.production
    # ports:
    #   - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d -U $$POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
