name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: 📝 Write .env.production from secret
        run: echo "${{ secrets.ENV_PRODUCTION }}" > .env.production

      - name: 📦 Export .env.production
        run: |
          grep -v '^#' .env.production | grep -E '^[A-Za-z_][A-Za-z0-9_]*=' >> $GITHUB_ENV

      - name: 🚀 Start PostgreSQL
        run: |
          docker run -d \
            --name postgres \
            -e POSTGRES_USER=$DB_USERNAME \
            -e POSTGRES_PASSWORD=$DB_PASSWORD \
            -e POSTGRES_DB=$DB_NAME \
            -p $DB_PORT:5432 \
            --health-cmd="pg_isready -U $DB_USERNAME" \
            --health-interval=10s \
            --health-timeout=5s \
            --health-retries=5 \
            postgres:13

      - name: 🕒 Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            if docker exec postgres pg_isready -U $DB_USERNAME; then
              echo "Postgres is ready"
              break
            fi
            sleep 3
          done

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏗️ Build app
        run: npm run build

      - name: 📜 Run migrations
        run: npm run typeorm -- migration:run

      - name: 🔎 Run unit tests
        run: npm run test

      - name: 🧪 Run e2e tests
        run: npm run test:e2e
